
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password:
  host: db
  # username: <%= ENV['SRC_DATABASE_USER'] %>
  # password: <%= ENV['SRC_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: src_development

test:
  <<: *default
  database: src_test
production:
  <<: *default
  database: src_production
