# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 569da14daa453ab833bc879ce6535f949bd0bcc92ce983a78d183ad317a8cf5aecf6b9b407b056e0f3a58cbc2d1818f82f0e0ecf1b9b9c0f5d04ca0d68b3a229

test:
  secret_key_base: 08b9898a9a07face54f6164290e52371c5ef8200d2d2feab662f9d4740fe7fe53c07eb8bdb5b30c54480a0e0ef23b0484ab7e7f02b7269848cf6b2eff63bf75a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
